//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolPowerTool.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VisibleWhenSelected")]
        public global::Microsoft.Windows.Controls.DataGridRowDetailsVisibilityMode ShowDetails {
            get {
                return ((global::Microsoft.Windows.Controls.DataGridRowDetailsVisibilityMode)(this["ShowDetails"]));
            }
            set {
                this["ShowDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SolutionFilename {
            get {
                return ((string)(this["SolutionFilename"]));
            }
            set {
                this["SolutionFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Projects")]
        public global::SolPowerTool.App.ViewModels.ControlTabs SelectedControlTab {
            get {
                return ((global::SolPowerTool.App.ViewModels.ControlTabs)(this["SelectedControlTab"]));
            }
            set {
                this["SelectedControlTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Projects")]
        public global::SolPowerTool.App.ViewModels.ProjectTabs SelectedProjectsTab {
            get {
                return ((global::SolPowerTool.App.ViewModels.ProjectTabs)(this["SelectedProjectsTab"]));
            }
            set {
                this["SelectedProjectsTab"] = value;
            }
        }
    }
}
